// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eslfcjhnaojghzuswpgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbGZjamhuYW9qZ2h6dXN3cGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODcyMzIsImV4cCI6MjA2NDQ2MzIzMn0.NdhfRgC8fvdQ-XxPiVSUkffQiayg0NZnwaixC12Ey5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);